FROM apache/airflow:2.8.1-python3.11

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir \
    "dbt-core>=1.7.0,<1.9.0" \
    "dbt-postgres>=1.7.0,<1.9.0" \
    "confluent-kafka>=2.3.0" \
    "kafka-python-ng>=2.2.2" \
    "psycopg2-binary>=2.9.9" \
    "faker>=22.5.1"
